baseURL = "https://www.jsaari.com/"
languageCode = "en"
title = "Jim Saari Portfolio"

disableKinds = ["taxonomy", "taxonomyTerm"]

# sectionPagesMenu = "main"

[menu]
  [[menu.main]]
    identifier = "posts"
    title = "Blog"
    url = "/blog/"

[params]
  description = "Personal developer portfolio for Jim Saari, passionate full stack web developer from Finland specialized working with modern JavaScript applications."
  repoURL = "https://github.com/jsaari97/jsaari-com"
  [params.social]
    [params.social.linkedin]
      type = "linkedin"
      url = "https://www.linkedin.com/in/jim-saari"
    [params.social.github]
      type = "github"
      url = "https://github.com/jsaari97"
  [params.contact]
    name = "Jim Saari"
    phone = "+358 505 411606"
    location = "Kronoby, Finland"
    email = "jim.saari97@gmail.com"
  [params.ackee]
    server = "https://ackee.jsaari.com"
    domainId = "6251545d-4256-4034-b057-782a8059101c"
