baseURL = "https://www.jsaari.com/"
languageCode = "en"
title = "Jim Saari Portfolio"

disableKinds = ["taxonomy", "taxonomyTerm"]

summaryLength = 25

[menu]
  [[menu.main]]
    identifier = "home"
    title = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "projects"
    title = "Projects"
    url = "/projects/"
    weight = 20
  [[menu.main]]
    identifier = "posts"
    title = "Blog"
    url = "/blog/"
    weight = 30

[params]
  description = "Personal developer portfolio for Jim Saari, passionate full stack web developer from Finland specialized working with modern JavaScript applications."
  repoURL = "https://github.com/jsaari97/jsaari-com"
  dateFormat = "2 January, 2006"
  [params.social]
    [params.social.linkedin]
      type = "linkedin"
      url = "https://www.linkedin.com/in/jim-saari"
    [params.social.github]
      type = "github"
      url = "https://github.com/jsaari97"
  [params.contact]
    name = "Jim Saari"
    nameShort = "Jim"
    phone = "+358 505 411606"
    location = "Kronoby, Finland"
    email = "jim.saari97@gmail.com"
  [params.ackee]
    server = "https://ackee.jsaari.com"
    domainId = "6251545d-4256-4034-b057-782a8059101c"

[imaging]
resampleFilter = "box"
quality = 75
anchor = "smart"
bgColor = "#fafafb"